[project]
name = "nicegui-admin"
version = "0.1.0.dev0"
description = "A admin Panel besed on NiceGUI."
authors = [
    { name = "Julius Koenig", email = "info@bastelquartier.de" },
]
dependencies = [
    "nicegui>=3.8.0",
]
requires-python = ">=3.10"
readme = "README.md"
keywords = ["nicegui", "gui", "tools", "niceguitools"]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[dependency-groups]
sqlmodel = [
    "sqlmodel>=0.0.37",
]
dev = [
    "pywebview>=6.1",
    "starlette-admin>=0.16.0",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[tool.uv]
default-groups = "all"

